[package]
name = "dlopen"
version = "0.1.0"
edition = "2021"

[dependencies]
jni-loader = { path = "../../jni-loader", features = ["inline-asm"] }
env_logger = "0.11.1"
anyhow = "1.0.79"
libc = "0.2.153"
