[package]
name = "spotify-hashcash"
version = "0.1.0"
edition = "2021"
autobins = false

[[example]]
name = "spotify-hashcash"
path = "src/main.rs"

[dependencies]
jni-loader = { path = "../../jni-loader" }
hex = "0.4.3"
env_logger = "0.11.1"
libc = "0.2.153"
